import { MedusaRequest, MedusaResponse } from "@medusajs/framework/http"
import { Modules } from "@medusajs/framework/utils"

/**
 * Authenticate customer with Vipps OAuth
 * POST /auth/user/vipps
 * This endpoint creates a session token for a customer authenticated via Vipps
 */
export async function POST(
  req: MedusaRequest,
  res: MedusaResponse
): Promise<void> {
  const { email, provider_metadata } = req.body

  if (!email) {
    return res.status(400).json({ message: "Email is required" })
  }

  try {
    const container = req.scope
    const authModule = container.resolve(Modules.AUTH)
    const userModule = container.resolve(Modules.USER)

    // Find customer by email
    const users = await userModule.listUsers({ email })
    const customer = users[0]

    if (!customer) {
      return res.status(404).json({ message: "Customer not found" })
    }

    // Use Medusa's built-in auth flow to create a session
    // For OAuth providers, we need to use the auth module's authenticate method
    // But since createSession doesn't exist, we'll use the provider identity directly
    
    // Try to get the auth identity for Vipps provider
    // Since we can't query by entity_id, we'll need to authenticate using the provider
    
    // The simplest approach is to use the auth module's authenticate method if available
    // Otherwise, we'll need to manually create a session token
    
    // For now, let's try to use the login method with the provider
    // But this might not work since Vipps is an OAuth provider
    
    // Actually, in Medusa v2, we need to use the auth provider's authenticate method
    // But since we're in a callback, we know the user is authenticated
    // We just need to generate a session token
    
    // The best approach is to use the auth module's login or authenticate method
    // But since those don't work for OAuth, we might need to manually generate a JWT
    
    // Let's try using the store auth endpoint approach instead
    // We'll create a session by calling the internal auth flow
    
    // For Medusa v2, the session token is typically generated by the auth module
    // when authenticating with a provider. Since we already have the auth identity,
    // we might be able to use it to create a session.
    
    // However, since createSession doesn't exist, we might need to use a workaround
    // One option is to use the JWT service directly if available
    
    // For now, let's return an error indicating we need to implement this differently
    return res.status(501).json({ 
      message: "Vipps OAuth authentication endpoint not yet implemented. Please use the storefront auth flow." 
    })
  } catch (error: any) {
    console.error("Vipps auth error:", error)
    return res.status(500).json({ message: error.message || "Authentication failed" })
  }
}

